### ISSUE TITLE
[Compat] doesn't capture new screens with randompatches

### ISSUE THREAD

**Issue by supersaiyansubtlety** [Minenash/Seamless-Loading-Screen#12]
When using this mod and random patches, no new screenshots are saved when exiting a world. 

random settings:
[randompatches.toml](https://github.com/Minenash/Seamless-Loading-Screen/files/5859517/randompatches.txt)

- `randompatches-2.1.9-fabric`
- `seamless-loading-screen-1.1.0+1.16`

**Comment by Minenash** [comment]
Does setting `return_to_main_menu_after_disconnect` to false fix it?

**Comment by supersaiyansubtlety** [comment]
It doesn't

**Comment by Minenash** [comment]
What about adding `GameMenuScreen` to the mixing blacklist?

**Comment by supersaiyansubtlety** [comment]
Yup! Thanks

**Comment by Minenash** [comment]
Unless there's more demand for it, I don't think I'll add compat with that feature, at least for now. The way random patches applies the mixin, there doesn't seem like a way to do it without them moving the logic part of their code to a non-mixin class, so i can mixin it.

**Comment by supersaiyansubtlety** [comment]
Sounds good, that's why randompatches lets you blacklist mixins anyways. 

Thanks for pinpointing the issue.

**Comment by srnyx** [comment]
> What about adding `GameMenuScreen` to the mixing blacklist?

How do I do this? Like how do I format it?
This is what it is by default: `mixin_blacklist = []`

**Comment by supersaiyansubtlety** [comment]
`mixin_blacklist = ["GameMenuScreen"]`

**Comment by srnyx** [comment]
> mixin_blacklist = ["GameMenuScreen"]

Thanks!

**Comment by srnyx** [comment]
Wait, but look:
`	- GameMenuScreen:
	- Required for making Minecraft show the main menu screen after disconnecting rather than the Realms or multiplayer screen.
	- If Seamless Loading Screen is installed, this is disabled, and FinishQuit is used instead.`

**Comment by supersaiyansubtlety** [comment]
Oh right, I forgot that since randompatches 'added compatibility' with seamless loading, I've had to just uninstall randompatches from my client. 

Maybe try blacklisting `"FinishQuit"` as well?

**Comment by Minenash** [comment]
Okay, so I know what's happening now. In one of my recent releases, I changed the quit method to static (this was to add support for taking the screenshot when closing the window, not just the quit button), and randompatches is calling it thinking it's not static.

The release that changed this is v1.3.0, so you can downgrade until randompatches releases a fix (also cool to know they added support :slightly_smiling_face: )

**Comment by TheRandomLabs** [comment]
Fixed!

**Comment by srnyx** [comment]
> Fixed!

Dang, that was fast, thank you!

**Comment by supersaiyansubtlety** [comment]
I'm still having issues, with only these mods installed:
- `seamless-loading-screen-1.3.1+1.16.2.jar`
- `randompatches-2.4.1-fabric.jar`
- `fabric-api-0.30.0+1.16.jar`
I get a crash upon exiting a world

[latest.log](https://pastebin.com/5mtDeeQL)

[crash.txt](https://pastebin.com/nV357HHJ)

**Comment by Minenash** [comment]
Are you using realms? If not, does it happen without randompatches?

**Comment by supersaiyansubtlety** [comment]
No realms, just singleplayer, and it only happens when I have both randompatches and seamless.

**Comment by Minenash** [comment]
Just took a look at their mixin, and I see where the problem is. To sync with the render thread, I use a screen and take the screenshot in the render. When Fabric API 0.30.0 came out with the new screen api, if a screen's render method was called during another screen's render method, then it'd crash the way it did for you. My patch solution by disabling a null check, and giving what was null, a value. But to break other stuff, I only made it run during when it was quiting. However the randompatches mixin skips this. This (probably) could be fixed by adding this line into the mixin:
```java
SeamlessLoadingScreen.isDisconnecting = true;
```
I might find a better workaround, (that's not fapi 0.30.0+ *only*), but there was also the idea of fixing the source issue in fapi's screen api

**Comment by TheRandomLabs** [comment]
Thanks for the easy fix! Let me know if you end up finding a better workaround. 😄

**Comment by srnyx** [comment]
_This thread is why I like Fabric better than Forge lmfao_
